version: '3.7'
services:
 # frontend:
 #   container_name: frontend
 #   image: harrisonwaffel/aseekerfrontend
 #   build:
 #     context: ./aseekerfrontend
 #     dockerfile: Dockerfile
 #   ports:
 #     - '1337:80'
 #   networks:
 #     - aseeker

 database:
   container_name: ASeeker-transcription-database
   image: 'mysql:5.7'
   volumes:
     - 'db_data:/var/lib/mysql'
     - './mysql:/tmp/db'
   command: '--init-file /tmp/db/sqlStartup.sql'
   restart: always
   ports:
     - '3306:3306'
   environment:
     MYSQL_ROOT_PASSWORD: aseeker
   networks:
     - aseeker

 middware:
   container_name: golang-RPC-middleware
   image: "harrisonwaffel/aseekermiddleware"
   build:
     context: ./golangRpc
     dockerfile: Dockerfile
   ports:
     - '1177:1177'
   networks:
     - aseeker

 deepspeech:
   container_name: deepspeech
   # deploy:
   #   resources:
   #     reservations:
   #       cpus: '4.5'
   #       memory: 220M
   image: harrisonwaffel/aseekerdeepspeech
   build:
      context: ./deepspeech
      dockerfile: Dockerfile
   volumes:
     - 'aseeker_media:/audio'

   ports:
     - '5000:5000'
   networks:
     - aseeker

#for a good networking tutorial see https://runnable.com/docker/docker-compose-networking
networks:
    aseeker:
        # use the bridge driver
        driver: bridge
        ipam:
            driver: default


volumes:
  db_data: {}
  aseeker_media: {}
