version: '3.7'
services:

 frontend:
   deploy:
     mode: replicated
     replicas: 1
   image: harrisonwaffel/aseekerfrontend
   build:
     context: ./aseekerfrontend
     dockerfile: Dockerfile
   ports:
     - '1337:80'
   networks:
     - aseeker

 database:
   image: 'mysql:5.7'
   deploy:
     mode: global
   volumes:
     - 'db_data:/var/lib/mysql'
     - './mysql:/tmp/db'
   command: '--init-file /tmp/db/sqlStartup.sql'
   restart: always
   ports:
     - '3306:3306'
   environment:
     MYSQL_ROOT_PASSWORD: aseeker
   networks:
     - aseeker


 middware:
   image: harrisonwaffel/aseekermiddleware
   build:
     context: ./golangRpc
     dockerfile: Dockerfile
   deploy:
     mode: replicated
     replicas: 1
   ports:
     - '1177:1177'
   networks:
     - aseeker


 deepspeech:
   build:
      context: ./deepspeech
      dockerfile: Dockerfile
   image: harrisonwaffel/aseekerdeepspeech
   deploy:
     mode: replicated
     replicas: 1
   volumes:
     - 'aseeker_media:/audio'
   ports:
     - '5000:5000'
   networks:
     - aseeker

networks:
    aseeker:
      driver: overlay


volumes:
  db_data: {}
  aseeker_media: {}
